have rule identifier available in RuleSlot
rtucek/vue-query-builder pull request #83
Opened 2022-03-07 14:23 UTC by DJManuel

This PR adds the ruleIdentifier to the RuleSlot Props to cleraly identify the exact rule that is being used. Related to Issue #81

2022-03-07 23:08 UTC, rtucek commented
Please consider the following TODOs:

- [ ] Fix TS builds
- [ ] The `RuleSlotProps` type [interface](https://github.com/rtucek/vue-query-builder/blob/main/src/types.ts#L47) needs to be extended for having TS support
- [ ] Documentation needs to be updated on the [related slot page](https://rtucek.github.io/vue-query-builder/styling.html#rule-slot)
- [ ] Add a [unit test](https://github.com/rtucek/vue-query-builder/blob/main/tests/unit/slots.spec.ts#L172)

2022-03-08 12:19 UTC, DJManuel commented
TS builds and interface has been fixed. In the Documentation some mention has been added for it.
I am sorry, but I am quite new with jest, so I hope the unit test implementation is fine how it is done.

2022-03-09 23:08 UTC, rtucek requested changes
Thx for your contribution.

I only found 2 minor things :wink:

2022-03-14 10:09 UTC, DJManuel commented
Those two minor things are corrected and should be ready to be merged. Thank you!

2022-03-15 16:08 UTC, DJManuel commented
The Failing CI Testing seems to be a permissions issue:
[See here](https://github.com/rtucek/vue-query-builder/runs/5554379983?check_suite_focus=true#step:1:13)
[compared to a working PR](https://github.com/rtucek/vue-query-builder/runs/4909314511?check_suite_focus=true#step:1:13)
I am not quite sure exactly, but I would guess some of those token items would need to be "write" in order to create a comment on this PR.

2022-03-22 23:35 UTC, rtucek commented
The test itself is fine and passes. The Github action pipeline fails because it can't upload the code coverage report (which is supposed to show up as a comment here). Apparently, I assumed this will "just work" regardless if I or someone else will open a PR. This is a fundamental [problem with Github](https://github.community/t/github-actions-are-severely-limited-on-prs/18179#M9249) itself... I've removed the coverage report action as it will only work if I open the PR by myself :/

In any case - thank you very much for you contribution :pray:

2022-03-22 23:36 UTC, rtucek approved these changes

2022-03-22 23:44 UTC, merged